import type { Company } from '../types/company'
import type { AgentMessage, AgentAction } from '../types/agent'
import type { Campaign } from '../types/meta'

const baseCampaigns: Campaign[] = [
  {
    id: 'camp-1',
    companyId: 'comp-1',
    name: 'Leads WhatsApp - Imoveis',
    objective: 'LEADS',
    status: 'ACTIVE',
    budget: 150,
    budgetType: 'DAILY',
    startDate: '2025-01-15',
    adSets: [],
    ads: [],
    metrics: { impressions: 45000, reach: 32000, clicks: 1800, ctr: 4.0, cpc: 0.83, cpm: 3.33, spend: 2340, conversions: 187, costPerConversion: 12.51, roas: 4.2, frequency: 1.4 },
    agentId: 'agent-leads-1',
    automationEnabled: true,
    rules: [],
  },
  {
    id: 'camp-2',
    companyId: 'comp-1',
    name: 'Trafego - Landing Terrenos',
    objective: 'TRAFFIC',
    status: 'ACTIVE',
    budget: 80,
    budgetType: 'DAILY',
    startDate: '2025-01-20',
    adSets: [],
    ads: [],
    metrics: { impressions: 38000, reach: 28000, clicks: 1520, ctr: 4.0, cpc: 0.74, cpm: 2.95, spend: 1120, conversions: 94, costPerConversion: 11.91, roas: 3.8, frequency: 1.36 },
    agentId: 'agent-traffic-1',
    automationEnabled: true,
    rules: [],
  },
  {
    id: 'camp-3',
    companyId: 'comp-1',
    name: 'Remarketing - Visitantes Site',
    objective: 'SALES',
    status: 'ACTIVE',
    budget: 50,
    budgetType: 'DAILY',
    startDate: '2025-02-01',
    adSets: [],
    ads: [],
    metrics: { impressions: 12000, reach: 8500, clicks: 680, ctr: 5.67, cpc: 1.0, cpm: 5.67, spend: 680, conversions: 62, costPerConversion: 10.97, roas: 5.1, frequency: 1.41 },
    agentId: 'agent-sales-1',
    automationEnabled: true,
    rules: [],
  },
]

const comp2Campaigns: Campaign[] = [
  {
    id: 'camp-4',
    companyId: 'comp-2',
    name: 'Vendas - Colecao Verao',
    objective: 'SALES',
    status: 'ACTIVE',
    budget: 200,
    budgetType: 'DAILY',
    startDate: '2025-01-10',
    adSets: [],
    ads: [],
    metrics: { impressions: 85000, reach: 62000, clicks: 3400, ctr: 4.0, cpc: 1.18, cpm: 4.71, spend: 4000, conversions: 280, costPerConversion: 14.29, roas: 6.2, frequency: 1.37 },
    agentId: 'agent-sales-2',
    automationEnabled: true,
    rules: [],
  },
  {
    id: 'camp-5',
    companyId: 'comp-2',
    name: 'Engajamento - Instagram',
    objective: 'ENGAGEMENT',
    status: 'ACTIVE',
    budget: 60,
    budgetType: 'DAILY',
    startDate: '2025-01-25',
    adSets: [],
    ads: [],
    metrics: { impressions: 120000, reach: 95000, clicks: 4800, ctr: 4.0, cpc: 0.25, cpm: 1.0, spend: 840, conversions: 4800, costPerConversion: 0.18, roas: 0, frequency: 1.26 },
    agentId: 'agent-engagement-2',
    automationEnabled: true,
    rules: [],
  },
]

const comp3Campaigns: Campaign[] = [
  {
    id: 'camp-6',
    companyId: 'comp-3',
    name: 'Cadastros - Aulas Gratis',
    objective: 'REGISTRATION',
    status: 'ACTIVE',
    budget: 100,
    budgetType: 'DAILY',
    startDate: '2025-02-01',
    adSets: [],
    ads: [],
    metrics: { impressions: 55000, reach: 42000, clicks: 2200, ctr: 4.0, cpc: 0.64, cpm: 2.55, spend: 1400, conversions: 350, costPerConversion: 4.0, roas: 8.5, frequency: 1.31 },
    agentId: 'agent-registration-3',
    automationEnabled: true,
    rules: [],
  },
  {
    id: 'camp-7',
    companyId: 'comp-3',
    name: 'Funil Completo - Mentoria',
    objective: 'FUNNEL',
    status: 'ACTIVE',
    budget: 300,
    budgetType: 'DAILY',
    startDate: '2025-01-05',
    adSets: [],
    ads: [],
    metrics: { impressions: 180000, reach: 140000, clicks: 7200, ctr: 4.0, cpc: 0.83, cpm: 3.33, spend: 6000, conversions: 120, costPerConversion: 50.0, roas: 12.0, frequency: 1.29 },
    agentId: 'agent-funnel-3',
    automationEnabled: true,
    rules: [],
  },
]

export const mockCompanies: Company[] = [
  {
    id: 'comp-1',
    name: 'Vida Nova Imobiliaria',
    industry: 'Imobiliario',
    website: 'https://vidanova.com.br',
    whatsapp: '+5574999999999',
    monthlyBudget: 8400,
    status: 'active',
    createdAt: '2025-01-10',
    goals: [
      { id: 'g1', objective: 'LEADS', target: 500, metric: 'leads/mes', currentValue: 343, deadline: '2025-03-31', status: 'on_track' },
      { id: 'g2', objective: 'TRAFFIC', target: 5000, metric: 'cliques/mes', currentValue: 3320, deadline: '2025-03-31', status: 'on_track' },
    ],
    campaigns: baseCampaigns,
    agents: [
      { id: 'a1', type: 'orchestrator', status: 'active', lastAction: 'Redistribuiu orcamento entre campanhas', lastActionAt: '2025-02-15T10:30:00', actionsToday: 3, performance: 94 },
      { id: 'a2', type: 'leads', status: 'working', lastAction: 'Otimizou publico lookalike 2%', lastActionAt: '2025-02-15T11:00:00', actionsToday: 7, performance: 92 },
      { id: 'a3', type: 'traffic', status: 'active', lastAction: 'Pausou anuncio com CTR < 1%', lastActionAt: '2025-02-15T09:45:00', actionsToday: 5, performance: 88 },
      { id: 'a4', type: 'creative', status: 'idle', lastAction: 'Sugeriu 3 novas variacoes de criativo', lastActionAt: '2025-02-15T08:00:00', actionsToday: 2, performance: 90 },
      { id: 'a5', type: 'audience', status: 'active', lastAction: 'Criou publico personalizado de visitantes 30d', lastActionAt: '2025-02-15T10:15:00', actionsToday: 4, performance: 91 },
    ],
  },
  {
    id: 'comp-2',
    name: 'Bella Moda Feminina',
    industry: 'E-commerce / Moda',
    website: 'https://bellamoda.com.br',
    whatsapp: '+5511988888888',
    monthlyBudget: 7800,
    status: 'active',
    createdAt: '2025-01-15',
    goals: [
      { id: 'g3', objective: 'SALES', target: 800, metric: 'vendas/mes', currentValue: 560, deadline: '2025-03-31', status: 'on_track' },
      { id: 'g4', objective: 'ENGAGEMENT', target: 15000, metric: 'engajamentos/mes', currentValue: 9600, deadline: '2025-03-31', status: 'ahead' },
    ],
    campaigns: comp2Campaigns,
    agents: [
      { id: 'a6', type: 'orchestrator', status: 'active', lastAction: 'Aumentou budget de vendas em 15%', lastActionAt: '2025-02-15T10:00:00', actionsToday: 4, performance: 96 },
      { id: 'a7', type: 'sales', status: 'working', lastAction: 'Ativou dynamic ads para catalogo', lastActionAt: '2025-02-15T11:20:00', actionsToday: 8, performance: 95 },
      { id: 'a8', type: 'engagement', status: 'active', lastAction: 'Impulsionou post com 12% engajamento', lastActionAt: '2025-02-15T09:30:00', actionsToday: 6, performance: 93 },
      { id: 'a9', type: 'creative', status: 'working', lastAction: 'Testando carousel vs video para colecao', lastActionAt: '2025-02-15T10:45:00', actionsToday: 5, performance: 91 },
    ],
  },
  {
    id: 'comp-3',
    name: 'Academia Saber Digital',
    industry: 'Educacao / Infoprodutos',
    website: 'https://saberdigital.com.br',
    whatsapp: '+5521977777777',
    monthlyBudget: 12000,
    status: 'active',
    createdAt: '2025-01-05',
    goals: [
      { id: 'g5', objective: 'REGISTRATION', target: 1000, metric: 'cadastros/mes', currentValue: 700, deadline: '2025-03-31', status: 'on_track' },
      { id: 'g6', objective: 'FUNNEL', target: 200, metric: 'vendas funil/mes', currentValue: 120, deadline: '2025-03-31', status: 'behind' },
    ],
    campaigns: comp3Campaigns,
    agents: [
      { id: 'a10', type: 'orchestrator', status: 'active', lastAction: 'Priorizou funil de mentoria', lastActionAt: '2025-02-15T10:10:00', actionsToday: 5, performance: 93 },
      { id: 'a11', type: 'registration', status: 'working', lastAction: 'Otimizou instant form — conversao subiu 22%', lastActionAt: '2025-02-15T11:30:00', actionsToday: 9, performance: 97 },
      { id: 'a12', type: 'funnel', status: 'alert', lastAction: 'ALERTA: MOFU com queda de 15% na conversao', lastActionAt: '2025-02-15T11:45:00', actionsToday: 6, performance: 78 },
      { id: 'a13', type: 'copy', status: 'active', lastAction: 'Criou 5 variacoes de headline para aula gratis', lastActionAt: '2025-02-15T09:00:00', actionsToday: 4, performance: 89 },
      { id: 'a14', type: 'budget', status: 'active', lastAction: 'Realocou R$50/dia do awareness pro funil', lastActionAt: '2025-02-15T08:30:00', actionsToday: 3, performance: 92 },
    ],
  },
]

export const mockMessages: AgentMessage[] = [
  {
    id: 'm1', from: 'leads', to: 'broadcast', type: 'insight', priority: 'high',
    subject: 'Publico feminino 25-34 converte 40% mais',
    content: 'Na empresa Vida Nova, o segmento feminino 25-34 anos tem CPL de R$8.20 vs R$14.30 do restante. Recomendo que todos os agentes priorizem esse segmento.',
    timestamp: '2025-02-15T10:30:00', read: false,
  },
  {
    id: 'm2', from: 'sales', to: 'creative', type: 'request', priority: 'medium',
    subject: 'Preciso de criativos em video curto',
    content: 'Videos de 15s estao com ROAS 3x maior que imagens na Bella Moda. Preciso de mais variacoes em video formato Reels.',
    timestamp: '2025-02-15T10:45:00', read: false,
  },
  {
    id: 'm3', from: 'funnel', to: 'orchestrator', type: 'alert', priority: 'critical',
    subject: 'MOFU da Saber Digital com queda critica',
    content: 'O meio do funil da Academia Saber Digital caiu 15% em conversao nos ultimos 3 dias. Publico esta saturado. Preciso de novos criativos e segmentacao urgente.',
    timestamp: '2025-02-15T11:00:00', read: false,
  },
  {
    id: 'm4', from: 'orchestrator', to: 'broadcast', type: 'recommendation', priority: 'high',
    subject: 'Realocar verba: awareness → funil',
    content: 'Baseado nos dados de todas as empresas, campanhas de awareness estao com ROI abaixo do aceitavel. Recomendo mover 30% do budget de awareness para funil e leads.',
    timestamp: '2025-02-15T11:15:00', read: false,
  },
  {
    id: 'm5', from: 'audience', to: 'leads', type: 'insight', priority: 'medium',
    subject: 'Novo lookalike pronto — compradores 1%',
    content: 'Criei um lookalike 1% baseado nos compradores dos ultimos 90 dias da Vida Nova. Recomendo testar com budget de R$30/dia antes de escalar.',
    timestamp: '2025-02-15T11:30:00', read: false,
  },
  {
    id: 'm6', from: 'budget', to: 'orchestrator', type: 'report', priority: 'low',
    subject: 'Relatorio diario de orcamento',
    content: 'Gasto total hoje: R$3.300 de R$4.200 planejado. Vida Nova: 78% executado. Bella Moda: 82%. Saber Digital: 75%. Nenhum overspend detectado.',
    timestamp: '2025-02-15T12:00:00', read: true,
  },
]

export const mockActions: AgentAction[] = [
  { id: 'act1', agentRole: 'leads', companyId: 'comp-1', campaignId: 'camp-1', type: 'adjust_bid', description: 'Reduziu lance de R$15 para R$12 no conjunto "Mulheres 25-34"', status: 'completed', result: 'CPL caiu 18%', impact: { metric: 'CPL', before: 15.0, after: 12.51, change: -2.49, changePercent: -16.6 }, timestamp: '2025-02-15T08:30:00' },
  { id: 'act2', agentRole: 'traffic', companyId: 'comp-1', campaignId: 'camp-2', type: 'pause_ad', description: 'Pausou anuncio "Banner Azul v2" — CTR 0.8% abaixo do minimo', status: 'completed', result: 'CTR medio da campanha subiu para 4.0%', impact: { metric: 'CTR', before: 3.2, after: 4.0, change: 0.8, changePercent: 25 }, timestamp: '2025-02-15T09:00:00' },
  { id: 'act3', agentRole: 'sales', companyId: 'comp-2', campaignId: 'camp-4', type: 'scale_campaign', description: 'Aumentou budget de R$150/dia para R$200/dia — ROAS estavel acima de 5x', status: 'completed', result: 'Vendas aumentaram 28% sem queda de ROAS', impact: { metric: 'ROAS', before: 5.8, after: 6.2, change: 0.4, changePercent: 6.9 }, timestamp: '2025-02-15T09:30:00' },
  { id: 'act4', agentRole: 'registration', companyId: 'comp-3', campaignId: 'camp-6', type: 'change_targeting', description: 'Adicionou interesse "cursos online" e removeu "faculdade"', status: 'completed', result: 'Taxa de cadastro subiu 22%', impact: { metric: 'CPR', before: 5.2, after: 4.0, change: -1.2, changePercent: -23.1 }, timestamp: '2025-02-15T10:00:00' },
  { id: 'act5', agentRole: 'funnel', companyId: 'comp-3', campaignId: 'camp-7', type: 'send_alert', description: 'ALERTA: Conversao do MOFU caiu 15% — possivel fadiga de criativo', status: 'completed', result: 'Orquestrador notificado, criativos em revisao', timestamp: '2025-02-15T11:00:00' },
  { id: 'act6', agentRole: 'budget', companyId: 'comp-3', type: 'adjust_budget', description: 'Realocou R$50/dia do awareness para funil da Saber Digital', status: 'completed', result: 'Verba redistribuida com sucesso', impact: { metric: 'Budget Funil', before: 300, after: 350, change: 50, changePercent: 16.7 }, timestamp: '2025-02-15T11:30:00' },
]
